# Site settings
title: Devbox Setup
email: ian@iansutherland.ca
description: >
  Devbox setup instructions for Mac and Linux.
baseurl: "/devbox-setup" # the subpath of your site, e.g. /blog
url: "http://iansu.github.io" # the base hostname & protocol for your site
twitter_username: iansu
github_username:  iansu

# Build settings
markdown: kramdown
